### ISSUE TITLE
Filter Include + Exclude

### ISSUE THREAD

**Issue by kumy** [euzu/m3u-filter#1]
**Is your feature request related to a problem? Please describe.**
Want to extract a group of channel and removing some based on their title

**Describe the solution you'd like**
I wish my filter to:
- Include by Group matching a pattern
- Exclude by Title matching a pattern

**Describe alternatives you've considered**
- Delete the lines after processing? `sed`
- Use filter mode Discard, and use negative lookahead regex and use 2 rules, but the readme already mention it `lacks a few features like look around and backreferences.` 

**Additional context**
Thanks!

**Comment by euzu** [comment]
I wanted to make sure I understood this correctly. You want to remove certain channels within a group?

Currently the filters specified are either include or exclude filters. To implement your feature you would also need to run filters in series (filter pipe).

I still have to think about how the filters are linked because in this case include and exclude are mixed.

**Comment by euzu** [comment]
New release v0.9.0 deployed for this issue.

**Comment by kumy** [comment]
Thanks a lot, the new filter is working very well. Congrats!

Here is my conf now ;) With #2 the last 2 targets will have more sense in Kodi, and scrapers would work.
```yaml
    targets:                                                                                           
      - filename: france_fhd.m3u                                                                 
        filter: '(Group ~ "^FR\|\s+FRANCE FHD" OR Group ~ "^FR\|\s+CULTURE 4K") AND Title ~ "[^-]{2}$"'
        options: {ignore_logo: false}                                                                  
        rename:                                                                                        
          - {field: Title, new_name: $1, pattern: ^.*\|\s(.*)(\s\(.*)?}                                
        sort: {order: Asc}                                                                             
                                                                                                       
      - filename: movies.m3u                                                                           
        filter: 'Group ~ "^\|FR\|\s+" AND Url ~ "/movie/"'                                             
        options: {ignore_logo: true}                                                                   
        rename:                                                                                        
          - {field: Group, new_name: $1, pattern: ^.*\|\s(.*)(\s\(.*)?}                                
        sort: {order: Asc}                                                                             
                                                                                                       
      - filename: series.m3u                                                                           
        filter: 'Group ~ "^\|FR\|\s+" AND Url ~ "/series/"'                                            
        options: {ignore_logo: true}                                                                   
        rename:                                                                                        
          - {field: Group, new_name: $1, pattern: ^.*\|\s(.*)(\s\(.*)?}                                
        sort: {order: Asc}                                                                             
```

Thanks again
