### ISSUE TITLE
docker and docker compose deplyment error

### ISSUE THREAD

**Issue by aniel300** [euzu/m3u-filter#105]
am getting this error when trying to deploy it with docker compose
![image](https://github.com/user-attachments/assets/5ae59ada-38ce-4955-bd9a-47d26dfb1333)

**Comment by euzu** [comment]
@aniel300 can you paste your docker-compose file ?

**Comment by aniel300** [comment]
it looks like this
```  m3ufilter:
    container_name: m3ufilter
    image: m3u-filter
    user: "133:144"
    working_dir: /
    volumes:
      - $PERSIST/m3ufilter/config:/config
      - $PERSIST/m3ufilter/data:/data
      - $PERSIST/m3ufilter/backup:/backup
      - $PERSIST/m3ufilter/downloads:/downloads
    environment:
      - TZ=Europe/Paris
    ports:
      - "8901:8901"
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "/m3u-filter", "-p", "/config" "--healthcheck"]  
    #   interval: 30s  
    #   timeout: 10s   
    #   retries: 3     
    #   start_period: 10s```

**Comment by euzu** [comment]
Do you want to use the image which i have created on github or did you create your own image?

**Comment by aniel300** [comment]
i want to use ur image as i dont know how to build my own image from scratch yet

**Comment by euzu** [comment]
@aniel300 you compose file is wrong:

here is my compose file which i am using:

```yaml

services:
  m3u-filter:
    container_name: m3u-filter
    image: ghcr.io/euzu/m3u-filter:latest
    user: "133:144"
    working_dir: /
    volumes:
      - /opt/m3u-filter/config:/config
      - /opt/m3u-filter/data:/data
      - /opt/m3u-filter/.backup:/backup
      - /opt/m3u-filter/downloads:/downloads
    environment:
      - TZ=Europe/Paris
    ports:
      - "8901:8901"
    restart: unless-stopped
```

You need to write your own config files, because the config files are user specific.
In my environment i have a  linux server and put all the files under `/opt/m3u-filter`.
You need to adapt this your server.
