### ISSUE TITLE
in reverse proxy mode sharing one connection to provider on same live tv channel

### ISSUE THREAD

**Issue by aniel300** [euzu/m3u-filter#116]
the idea is to use only 1 cxn back to the provider when watching the same channel from 2 or more clients using `proxy: reverse`. right now if u watch the same channel from 2 or more clients, each client will requires a cxn back to the provider.
more info on this here: https://github.com/euzu/m3u-filter/discussions/112 and https://github.com/sonroyaalmerol/m3u-stream-merger-proxy/issues/164

**Comment by aniel300** [comment]
can u also take a look at this? https://github.com/euzu/m3u-filter/issues/117

**Comment by euzu** [comment]
@aniel300 i have a first working version (i hope).  I have created a beta image for you. To use channel sharing you need to set 
a target option:
`share_live_streams`


```yaml
  targets:
    - name: xtream-local
      filename:
      filter: "!ALL_CHAN!"
      options: {ignore_logo: false, share_live_streams: true}
```
