### ISSUE TITLE
Suffix in mapping are also used as prefix

### ISSUE THREAD

**Issue by kumy** [euzu/m3u-filter#12]
**Describe the bug**
Defining a suffix in a mapping is also used as prefix.

**To Reproduce**
Excerpt from `mapping.yml`:
```
        - pattern: 'Name ~ "!start!TF1!~!Series?!~!(Films?)?!end!" OR Name ~ "!start!HD1!end!"'
          attributes:
            name: 'TF1 Séries Films'
            id: 'TF1SeriesFilms.fr'
            chno: '20'
            logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Logo_TF1_S%C3%A9ries_Films_2018.jpg'
          suffix:
            name: '<tag:quality>'
            group: 'FR|TNT'
          assignments:
             title: name
```
With this added `suffix.name`, the `tvg-name` result is as `tvg-name=" [HD]TF1 Séries Films [HD]"`

**Expected behavior**
I would have expected the suffix to only be used as a suffix not prefix such as `tvg-name="TF1 Séries Films [HD]"`

**Tried workaround**
I've tried to define a supplemental `prefix.name` with an empty string or even random content, but the output remain the same.

```
        - pattern: 'Name ~ "!start!TF1!~!Series?!~!(Films?)?!end!" OR Name ~ "!start!HD1!end!"'
          attributes:
            name: 'TF1 Séries Films'
            id: 'TF1SeriesFilms.fr'
            chno: '20'
            logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Logo_TF1_S%C3%A9ries_Films_2018.jpg'
          prefix:
            name: 'foo'
          suffix:
            name: '<tag:quality>'
            #group: 'FR|TNT'
          assignments:
             title: name
```
At least in such case I would have expected the output be be: `tvg-name="foo TF1 Séries Films [HD]"` but it's not ;)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
