### ISSUE TITLE
Server always returns http_port

### ISSUE THREAD

**Issue by blockloop** [euzu/m3u-filter#127]
**Describe the bug**

Something between 2.0.7 and 2.0.8 broke the port returned in server to always return the `http_port` in responses even when using https.

```
server:
  - name: local
    protocol: http
    host: localhost
    http_port: 8901
    https_port: 8443
    rtmp_port: 0
    timezone: America/Chicago
    message: Local

  - name: prod
    protocol: https
    host: example.xyz
    http_port: 8901
    https_port: 443
    rtmp_port: 0
    timezone: America/Chicago
    message: ""
```

this config on 2.0.7 returns `https://example.xyz:443`. On 2.0.8 it returns `https://example.xyz:8901`
