### ISSUE TITLE
ability to combine 2 or more line/ providers

### ISSUE THREAD

**Issue by aniel300** [euzu/m3u-filter#137]
ability to combine 2 or more line/ providers using either same domain or different domains

**Comment by euzu** [comment]
I dont understand what you mean. Can you describe it a little more .

**Comment by aniel300** [comment]
let say i have two m3u lines/ accounts from the same provider (either same domain or different domain) and they both have 1 cxn allow to each line. i would like the ability to group then together and then have the proxy load balance across them base on the defined allowed cxn. so in this case if 1 user is using 1 cxn from line 1, next user that starts watching will use the next line/cxn available from the next line and so on.

**Comment by aniel300** [comment]
let me know if u still confuse and i will try to break it down more

**Comment by aniel300** [comment]
i have some more ideas about this feature request, i will add it soon

**Comment by jojo141185** [comment]
It is certainly a lot of effort to implement, but in my view, the best approach for this feature request would be the following implementation:

1. Automated Content Identification and Backup Assignment:
- Automatically identify identical content across multiple providers using techniques like fuzzy matching (e.g., Levenshtein distance) and metadata comparison (e.g., title, release date, duration).
- Assign backup providers for each piece of content to ensure availability if the primary provider is unavailable or the content is being accessed by another user.

2. Fallback Mechanism:
- When a user requests content, the system should first attempt to retrieve it from the primary provider.
- If the primary provider is unavailable, the system should automatically redirect the request to a backup provider. This fallback should be seamless for the user.

3. Web Interface for Manual Editing:
Provide an easy-to-use web editor where administrators can:
- Search for content across providers.
- Review and manually adjust automated matches.
- Assign or modify backup providers as needed.

This implementation would ensure high availability and a smooth user experience while allowing for flexibility and manual intervention where needed.

**Comment by aniel300** [comment]
yes this all are good ideas. i still need to break down mines. btw this is related to that discussion i mentioned and the webui admin idea is a whole another discussion i wanted to tell you about but i don't want to overwhelm or push my luck with you, so u know one thing at the time.

**Comment by aniel300** [comment]
@jojo141185 my comment might be a little off because I though it was @euzu who replied.

**Comment by euzu** [comment]
@jojo141185 No, any help and contributions are welcome. The more people get involved, the better. So please don’t hesitate to share your opinion.

**Comment by euzu** [comment]
I have started working on this feature.

The initial implementation will support multiple credentials for the same provider.

This means that the content remains identical across these credentials and is fetched only once.
Requests to the provider should be distributed in a cyclic manner (using the Round Robin technique).
One of the challenges with handling multiple connections is that many providers disconnect the previous connection when a new one is opened. This behavior ensures that a new connection does not result in an "access denied" response. For the first version, we will ignore this issue and focus on enabling the basic functionality.

In the first step, we are assuming that the content is identical across different credentials for the same provider. This is because we currently lack the capability to determine whether the content provided by different providers might overlap or be identical. Addressing this challenge is a complex task and will require further investigation in the future.

This feature introduces "input aliases" for the same provider, assuming the content is identical but accessed using different credentials. This approach simplifies access management while ensuring that content is fetched only once, thereby improving efficiency.


@aniel300 and @jojo141185 any suggestions or improvements to this initial draft are highly welcome!

```yaml
- sources:
- inputs:
  - url: 'http://provider.net'
    name: my_provider
    username: xyz
    password: secret1
    aliases:
    - url: 'http://provider.net'
      username: abcd
      password: secret2
    - url: 'http://provider.net'
      username: defg
      password: secret3
  targets:
  - name: test
```

**Comment by aniel300** [comment]
@euzu u are cooking. am sending u a edit version of my latest break down when it comes to this via discord as i have new ideas and concerns.

**Comment by jojo141185** [comment]
@euzu I don't know if @aniel300 had the same thought when he opened this feature request. With my contribution I just wanted to try to describe and concretize this feature from my point of view, as there seem to have been open questions and unclarities for some time.
Your draft sounds like a solid initial approach! But in my perspective the greatest benefit would be a robust backup/failover system as described before. This would allow using different providers as backups or dynamically switching m3u filters to free alternatives when one provider is busy.  To achieve this, automated mapping of alternative channels (same content, different source/resolution) within or across providers is crucial, ideally with a web UI for manual adjustments.  This would maximize uptime and user experience.
In my opinion, this would make m3u-filter unrivaled and provide a killer feature that many users are looking for. However, I personally don't have a use for it at the moment and therefore probably can't contribute much concrete to this.
It's important to emphasize that achieving this, especially the automated mapping and fallback mechanism, will require significant effort in developing a user-friendly web UI.  A well-designed interface will be crucial for users to easily manage providers, review automated matches, and make manual adjustments.

**Comment by aniel300** [comment]
@jojo141185 i don't want anything done in the ui except for maybe fallbacks adjustment since i came up with a good way to do that via config. i actually prefer to do as much initial manual work in the config that way it can pay up in the long run. since u could change providers but your pre done work should work for the most part across provider and if anything, few tweaks might be need but that is about it. i have sent him a new edited broken-down logic on this and am waiting to see what he says. send me an invite on discord and i will send it to u.

**Comment by euzu** [comment]
@aniel300  here your ideas

```yaml
   url: '/xxx.txt'
   priority: 1,2,
   max_connections_per_line: option 1,5,3
```

`url` can be a texfile containing the provider url per line.
`priority` : prioritize the provider,  and use max connections from this provider, then use the next in line until max connections reached. if the same priority number is on 2 or more source/imput then the load balancer should loadbalance across them. i think this might be usefull to use different providers while doing loadbalancing across them. this idea is for the fallback thing and will define a tiered system as to how the proxy should handle fallbacks base on provider/priorites.

**Comment by jojo141185** [comment]
@euzu Thank you for your tireless efforts here. Unfortunately, I don't have a provider to use or test this feature. I am curious how you will implement the function regarding backup channels if it is an alternative provider with a different channel structure / naming.

@aniel300 The combination of flexible fuzzy matching techniques such as Levenshtein distance or Jaro-Winkler for the automatic assignment of channels or content by name with the highest possible hit rate is definitely necessary given the amount of content. The rules should be defined or laid down in the config. Nevertheless, in my opinion, a tabular overview of the active mapping would be useful for control purposes in order to refine the rules and view the result in real time. Because no matter how good the algorithm may be, I think that there will always be special cases where manual intervention or 1:1 mapping will be necessary. Visual support via the WEB-UI would certainly be a great help here.

**Comment by aniel300** [comment]
i totally agree with you

**Comment by nlitend1** [comment]
> [@jojo141185](https://github.com/jojo141185) currently it is only for 1:1 same providers. I need to think about howto wrap channel based provider mappings in this structure.
> 
> If you have any suggestions to the current implementation please let me know.



I'm no programmer (so I could be way off here), but perhaps an initial implementation (ahead of any potential webUI matching/fine-tuning.....(which would be absolutely amazing but as stated above would take a ton of work)) could be to have channels with the same name (or tvg-id) be paired/matched as backups/failovers/load balanced and have that based on an input priority level. 

I hesitate to mention another project publicly, but there is a much more basic level proxy/loadbalancer called  m3u-stream-merger-proxy that implements this sort of failover/multi-provider setup. Not sure if you've heard of it, but it may explain this better to see their site.

https://github.com/sonroyaalmerol/m3u-stream-merger-proxy

Again, just my 2 cents and you could be way past this point already, but I just want to contribute in any way that i can. I know @aniel300 from previous projects and i was mentioning some ideas to him and he recommended I share them with you here. 

Thanks again for the ongoing development! :)

**Comment by aniel300** [comment]
this is good info. i gave @euzu a broken down logic ideas of how things should work based on on what my brain was able to come up with when i did it. @euzu did shared some of those logic in here and am open to add them in here if needed. am also open to extra ideas/logic on how to make it better and cover more use cases. base on the private chats with @euzu i think he got a good idea on what i was trying to express on that break down and he is cooking however, because of the complexity of all this features, it requires a his attention. so we need to let him cook. and then once he has something to test, we shall go from there in terms of debugging, adding new features, etc. @nlitend1 i did send u my current logic, take a look at it and see if u have something extra to add. if u do, then when the time is right we can work on that.

**Comment by aniel300** [comment]
closing for the time being.

**Comment by alexeyand** [comment]
hello. first i could say thanks for your hard work.
cant figure out how to make auto-select provider.
line "aaaaaaaa" is always selected, even when more than one device is connected.
here is my config

```
sources:
- inputs:
  - url: 'http://provider.one:80'
    name: one
    epg_url: 'http://provider.one:80/xmltv.php?username=aaaaaaaa&password=bbbbbbbb'
    username: aaaaaaaa
    password: bbbbbbbb
    type: xtream
    enabled: true
    max_connections: 1
    aliases:
    - url: 'http://provider.one:80'
      max_connections: 1
      username: cccccccc
      password: dddddddd
    - url: 'http://provider.one:80'
      max_connections: 1
      username: eeeeeeee
      password: ffffffff
  targets:
  - name: all_channels
    output:
    - type: xtream
    filter: "!ALL_CHAN!"
    sort:
      match_as_ascii: true
      groups:
        order: asc
```

**Comment by euzu** [comment]
@alexeyand  input alias  is a new feature and is currently work in progress (it is not fully implemented).

An `alias` means you have multiple lines to the *same* provider and want to load balance between the accounts.

Is this what you want to do ?

**Comment by alexeyand** [comment]
exactly. because the access codes are sold with one connection, i just want to buy a lot of such codes and make an universal setup for all my devices 🤞

**Comment by euzu** [comment]
@alexeyand yes this is indeed what you can do with this setup. I will write you when i have a testable version

**Comment by euzu** [comment]
@alexeyand , @aniel300, @jojo141185   the alias provider setup is now working.
Pushed to master,  and beta docker images for x86_64  and aarch64.

**Comment by euzu** [comment]
The config should look like

```yaml
  - inputs:
    - url: 'http://provider.net'
      name: my_provider
      username: xyz
      password: secret1
      aliases:
      - name: my_provider_2 
        url: 'http://provider.net'
        username: abcd
        password: secret2
      - name: my_provider_3 
        url: 'http://provider.net'
        username: hjkd
        password: secret3
    targets:
    - name: test
```

**Comment by euzu** [comment]
@alexeyand could you test the feature?

**Comment by aniel300** [comment]
i have tested the liases one but it doesn't seem to be load balancing and it also doesn't seem possible to define max cxn for the root/main account which might be why it is mot load balancing

**Comment by euzu** [comment]
I have testes it and it.is working as expectes, can you share your config

**Comment by alexeyand** [comment]
I've been testing all day long and I have to say it works like magic 🤘🤘 check out the vid: https://youtu.be/bO6q1ihGkwg?si=2uZwoZR4o09KETQ1

sometimes are random disconnects happens (without auto-reconn), I haven't figured it out yet.

my config -


```
sources:
- inputs:
  - url: 'http://provider.one'
    type: xtream
    name: pyrographers
    username: aaaa
    password: aaaa
    epg_url: 'http://provider.one/xmltv.php?username=aaaa&password=aaaa'
    max_connections: 1
    headers:
      User-Agent: "VLC/3.0.21 LibVLC/3.0.21"
#      Accept: application/json
#      Accept-Encoding: gzip
    aliases:
    - name: pyrographers_2
      url: 'http://provider.one'
      username: bbbb
      password: bbbb
      max_connections: 1
    - name: pyrographers_3
      url: 'http://provider.one'
      username: cccc
      password: cccc
      max_connections: 1
    - name: pyrographers_4
      url: 'http://provider.one'
      username: dddd
      password: dddd
      max_connections: 1
    - name: pyrographers_5
      url: 'http://provider.one'
      username: eeee
      password: eeee
      max_connections: 1

```

**Comment by euzu** [comment]
@alexeyand good to know. About the connection loss, I asume you have reverse_proxy.stream.retry =true.
As l8ng as the provider does not return a forbidden it should reconnect.
Did you configure all 3 custom video settings to see what it could be?

**Comment by aniel300** [comment]
> I have testes it and it.is working as expected, can you share your config 

will do

**Comment by euzu** [comment]
@aniel300 as you can see in the post above it was successfully tested by alexeyand

**Comment by aniel300** [comment]
i will test again. probably am doing something wrong

**Comment by alexeyand** [comment]
@euzu , here is one of such conn-loss:
after that i set reverse proxy buffer off - it seems to have more stable, but im not so sure

<details><summary>LOG</summary>
<p>

```
[2025-03-22T16:29:38Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] Stream requested with headers: [("accept-language", "en_US"), ("host", "my-host.me:8901"), ("accept", "*/*"), ("user-agent", "VLC/3.0.17 LibVLC/3.0.17")]
[2025-03-22T16:29:38Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] Provider response  status: '200 OK' headers: {"date": "Sat, 22 Mar 2025 16:29:38 GMT", "content-type": "video/mp2t", "connection": "close", "access-control-allow-origin": "*"}
[2025-03-22T16:29:38Z DEBUG m3u_filter::api::api_utils] Responding stream request http://provider.one/live/aaaa/aaaa/717690.ts with status 200 OK, headers [("content-type", "video/mp2t"), ("connection", "close"), ("access-control-allow-origin", "*")]
[2025-03-22T16:29:38Z INFO  m3u_filter::api::model::streams::active_client_stream] Active clients: 1, active connections 2
[2025-03-22T16:31:40Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] stream provider http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:31:40Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] Reconnecting stream http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:31:41Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] stream provider http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:31:41Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] Reconnecting stream http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:31:41Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] stream provider http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:31:41Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] Reconnecting stream http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:31:42Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] stream provider http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:31:42Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] Reconnecting stream http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:31:43Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] stream provider http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:31:43Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] Reconnecting stream http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:31:43Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] stream provider http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:31:43Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] Reconnecting stream http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:33:09Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] stream provider http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:33:09Z DEBUG m3u_filter::api::model::streams::provider_stream_factory] Reconnecting stream http://provider.one/live/aaaa/aaaa/717690.ts
[2025-03-22T16:43:44Z INFO  m3u_filter::api::model::streams::active_client_stream] Active clients: 1, active connections 1
[2025-03-22T16:49:09Z INFO  m3u_filter::api::model::streams::active_client_stream] Active clients: 0, active connections 0

```
</p>
</details> 


<details><summary>CONFIG</summary>
<p>

```
threads: 0
api:
  host: 0.0.0.0
  port: 8901
  web_root: /web
working_dir: /data
backup_dir: /backup
custom_stream_response:
  channel_unavailable: /channel_unavailable.ts
  user_connections_exhausted: /user_connections_exhausted.ts
  provider_connections_exhausted: /provider_connections_exhausted.ts
user_access_control: true
schedules:
- schedule: 0 0  9/21  *  *  *  *
  targets: []
messaging:
  notify_on: []
log:
  sanitize_sensitive_info: false
  active_clients: true
  log_level: debug
update_on_boot: false
web_ui_enabled: true
web_auth:
  enabled: true
  secret: secret
  issuer: m3u_filter
  userfile: user.txt
reverse_proxy:
  stream:
    retry: true
    connect_timeout_secs: 5
    buffer:
      enabled: false
      size: 1024
  cache:
    enabled: true
    size: 1GB
    dir: "/cache"
  resource_rewrite_disabled: false
```

</p>
</details> 

<details><summary>SOURCES.TARGETS</summary>
<p>

```
  targets:
  - name: all_channels
    output:
    - type: xtream
    filter: "!ALL_CHAN!"
    sort:
      match_as_ascii: true
      groups:
        order: asc
```

</p>
</details> 

<details><summary>API-PROXY</summary>
<p>

```
server:
- name: external
  protocol: http
  host: my-host.me
  port: '8901'
  timezone: Etc/UTC
  message: Hello
user: []
use_user_db: true
```

</p>
</details>
