### ISSUE TITLE
suffix.groups has weird value

### ISSUE THREAD

**Issue by kumy** [euzu/m3u-filter#14]
**Describe the bug**
Since 0.9.7 the `group-title` have weird behavior, (seems related to #12 also).

1. concatenation with existing tag doesn't contains the separator
2. value is added as suffix and prefix bug #12

**To Reproduce**
Excerpt from `config.yml`
```
rename:
  - { field: group, new_name: "PROV1", pattern: "(.*)" }

```

`mapping.yml`
```
        - pattern: 'Name ~ "!start!TF1!~!Series?!~!(Films?)?!end!" OR Name ~ "!start!HD1!end!"'
          attributes:
            name: 'TF1 Séries Films'
            id: 'TF1SeriesFilms.fr'
            chno: '20'
            logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Logo_TF1_S%C3%A9ries_Films_2018.jpg'
          suffix:
            group: 'FR|TNT'
          assignments:
             title: name
```

**Expected behavior**
The actual output is `group-title="FR|TNTNIRVFR|TNT"`, but I would have expected `group-title="PROV1|FR|TNT"`

**Additional context**
Also linked to #12
