### ISSUE TITLE
M3uFilter error: Could not deserialize file "/data/all_channels/m3u.db" - File not found /data/all_channels/m3u.db

### ISSUE THREAD

**Issue by joazito** [euzu/m3u-filter#142]
I installed m3ufilter using docker compose and I think I set it up alright. I can access the WebUI and see the config based off the .yml files I created manually. I get this in the logs, all seems well:
[2025-01-02T01:11:33Z INFO  m3u_filter::processing::playlist_processor] {"stats": {"name":"https://[redacted url]","type":"xtream","errors":0,"raw":{"groups":327,"channels":46029},"processed":{"groups":326,"channels":46029},"took":"9 secs"}}

But when I try to retrieve the m3u by using ?get.php?username=aaaa&password=bbbb&type=m3u_plus&output=mpegts nothing happens and I see the error in the logs:

 [2025-01-02T01:14:34Z ERROR m3u_filter::api::m3u_api] M3uFilter error: Could not deserialize file "/data/all_channels/m3u.db" - File not found /data/all_channels/m3u.db

Sure enough, that file doesn't exist. Not sure if it's my fault or not.

**Comment by euzu** [comment]
@joazito this means that you did not create an m3u output. 

The rule is  to access the playlist through xtream api , you need an xtream output
If you wnt to access the m3u  api  you need an m3u output.

for example

```yaml
templates:
- name: SIMPLE_CHAN
  value: 'Group ~ ".*"'
- inputs:
    - type: xtream
      name: xtream
      persist:
      url: 'http://my-provider.com'
      username: test
      password: test.secret
  targets:
    - name: xtream
      filter: "!SIMPLE_CHAN!"
      output:
        - type: xtream       <- xtream api access
        - type: m3u           <- m3u api access
```

**Comment by joazito** [comment]
I added
`        - type: m3u
          filename: myprovider.m3u`

to the source.yml file and it wrote a myprovider.m3u file with only "#EXTM3U" written on it and nothing else.
The file "all_channels/m3u.db" is created but is only 1 Byte long. And the error message remains the same, "File not found [...]"

**Comment by euzu** [comment]
@joazito let me understand what you are trying to do.  Are you reading the m3u playlist from a server or from a local file ?

ok here is a sample which is working for  local network  and m3u playlist input  and m3u playlist output.

`config.yml`
```yaml
threads: 0
api:
  host: 0.0.0.0
  port: 8901
  web_root: ./web
working_dir: ./data
backup_dir: ./backup
update_on_boot: false
```

`api_proxy.yml`

```yaml
server:
- name: default
  protocol: http
  host: 192.168.2.3    <--- here should be the ip adddress of the m3u-filter server
  http_port: '8901'       <---- should be the same in config.yml
  https_port: '8443'
  rtmp_port: '0'
  timezone: Europe/Paris
  message: Welcome to m3u-filter
user:
- target: m3u_playlist              <-- this is a unique name for the target which need to be the same as in source.yml
  credentials:
  - username: test
    password: test.secret
    token: null
    proxy: redirect
    server: null
```
`source.yml`

```yaml
templates:
- name: ALL_CHAN
  value: 'Group ~ ".*"'
sources:
- inputs:
    - type: m3u
      url: 'http://myprovider.com/get.php?username=my_user&password=my_secret_password&type=m3u_plus&output=mpegts'
      epg_url: 'http://myprovider.com/xmltv.php?username=my_user&password=my_secret_password'
  targets:
    - name: m3u_playlist    <----- -- this is used in api_proxy.yml
      filter: "!ALL_CHAN!"
      options: {ignore_logo: true}
      output:
        - type: m3u
      sort:
        match_as_ascii: true
        groups:
          order: asc
```
