### ISSUE TITLE
epg ID mapping not working

### ISSUE THREAD

**Issue by orizzle** [euzu/m3u-filter#144]
I am trying a simple example below to try change a channel's EPG ID.  I'm confident I have the channel name correct but not sure if the config is incorrect or a bug

edit: github seems to be mangling my mappings.yml so here it is on pastebin: https://pastebin.com/raw/m4ihqwYu

```yaml
mappings:
  templates:
    - name: sports
      value: '(Title ~ "(?i)^USA Bally SPORTS DEPORTES HD$")'
    - name: source
      value: 'Url ~ ".*"'

  mapping:
    - id: sport-mapper
      mapper:
        - filter: '!sports!'
          pattern: "!source!"
          attributes:
            epg_channel_id: aande.us
```
