### ISSUE TITLE
getting this error for a particular provider

### ISSUE THREAD

**Issue by aniel300** [euzu/m3u-filter#147]
i can confirm i can download the m3u via my browser at my local network and my server network. `[2025-01-16T23:35:44Z ERROR m3u_filter::processing::playlist_processor] cant download input url: http://xxx.live:8080/player_api.php?username=***&password=***&action=get_live_categories  => Request failed with status 403 Forbidden`

**Comment by aniel300** [comment]
fixed it by commenting out 

```yml
        #Accept: application/json
        #Accept-Encoding: gzip
```

**Comment by euzu** [comment]
yes because the Problem is application/json. M3u Playlist is.plain text not json.  The server cant return json and quits with not allowed.

**Comment by aniel300** [comment]
this was for a xc target not a m3u one. does ur comment still stands?

**Comment by euzu** [comment]
Sorry  i didnt saw the url in your first post,  then i dont know why the server is complaining.

**Comment by aniel300** [comment]
> fixed it by commenting out
> 
> ```
>         #Accept: application/json
>         #Accept-Encoding: gzip
> ```

what does have these options enable do?

**Comment by euzu** [comment]
These are not options.
HTTP headers are key-value pairs sent in HTTP requests and responses. They provide additional information about the request or response, helping the client and server communicate effectively. 

HTTP headers are metadata that describe the content or behavior of an HTTP request or response.
Each header consists of a name and a value, e.g., `Content-Type: application/json.`

In the config you define the  `Request Headers` sent by the client (m3u-filter) to provide information to the server.
Example: `User-Agent` (describes the client making the request).

It is possible that Provider deny the request because your `User-Agent`is a desktop browser.

**Comment by aniel300** [comment]
umm am interested more on this. is there a section in the wiki for this?

**Comment by euzu** [comment]
This has nothing to do with m3u-filter.  This has to do with the HTTP/S Protocol.

**Comment by aniel300** [comment]
umm ok. thank u for the explanation btw

**Comment by aniel300** [comment]
does ur proxy support headers, agent, etc?

**Comment by euzu** [comment]
You can set headers individually for each input source.

Example input config for `xtream`
```yaml
sources:
  inputs:
    - type: xtream
      headers:
        User-Agent: "Mozilla/5.0 (AppleTV; U; CPU OS 14_2 like Mac OS X; en-us) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
        Accept: application/json
        Accept-Encoding: gzip
      url: 'http://localhost:8080'
      username: test
      password: test
```
