### ISSUE TITLE
Is the `tvg-logo` broken?

### ISSUE THREAD

**Issue by kumy** [euzu/m3u-filter#15]
**Describe the bug**
I just found from my latest output that the `tvg-logo` field doesn't seems to be replaced anymore.

**To Reproduce**
With current `HEAD`, and `0.9.7` (didn't tested old version because of the `mapping.yml` format changes introduced recently)
```
- pattern: 'Name ~ "!start!TF1!~!Series?!~!(Films?)?!end!" OR Name ~ "!start!HD1!end!"'
  attributes:
    name: 'TF1 Séries Films test'
    id: 'TF1SeriesFilms.fr'
    chno: '20'
    logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Logo_TF1_S%C3%A9ries_Films_2018.jpg'
  suffix:
    name: '<tag:quality>'
    group: 'FR|TNT'
  assignments:
     title: name
```

**Expected behavior**
Actually the `tvg-logo` is the same as the provider defined:

```
#EXTINF:-1 tvg-id="TF1SeriesFilms.fr" tvg-name="TF1 Séries Films test<tag:quality>" group-title="|FR| FRANCE FHDFR|TNT" tvg-chno="20" tvg-logo="http://foo.bar/images/france/TF1SeriesFilms.fr.png",TF1 Séries Films test<tag:quality>
```

Expected:
```
#EXTINF:-1 tvg-id="TF1SeriesFilms.fr" tvg-name="TF1 Séries Films test<tag:quality>" group-title="|FR| FRANCE FHDFR|TNT" tvg-chno="20" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/d/d4/Logo_TF1_S%C3%A9ries_Films_2018.jpg",TF1 Séries Films test<tag:quality>
```
