### ISSUE TITLE
KODI STRM playlist, no seek possible

### ISSUE THREAD

**Issue by euzu** [euzu/m3u-filter#150]
When creating strm playlist for KODI seek is not working.

**Comment by euzu** [comment]
@jojo141185 i have found out that kodi supports only seek operations when you write it tot the strm file.
I have tested successfully the following props:

```
#KODIPROP:seekable=true 
#KODIPROP:inputstream=inputstream.ffmpeg
#KODIPROP:http-reconnect=true 
http://........
```

Worked like a charm with reconnect and buffer in reverse proxy mode.

Can you test it with the latest master.  If you like you could look for more properties.

**Comment by euzu** [comment]
@jojo141185 is this enough or should we make this configurable ,  for live and non live streams.

**Comment by euzu** [comment]
@jojo141185   i have added new options:

`Strm` output has an additional option `strm_props`. 
This props are written to the strm file.

If `kodi_style` set to `true` the property `#KODIPROP:seekable=true|false` is added.
 If `kodi_style` set to `true` and `strm_props` is not given `#KODIPROP:inputstream=inputstream.ffmpeg`, `"#KODIPROP:http-reconnect=true` are written as default.

Example with fantasy props

```yaml

targets:
    - name: xtream
      filter: 'Group ~ ".*"'
      options:
         cleanup: true
         kodi_style: true
         strm_props:
          - '#KODIPROP:bubblegum=true
          - '#KODIPROP:inputstream=inpustream.bubblegum
      output:
        - type: strm
          filename: /tmp/kodi

```
