### ISSUE TITLE
Add xtream as output target to proxy xtream content with HLS

### ISSUE THREAD

**Issue by gymnae** [euzu/m3u-filter#16]
**Is your feature request related to a problem? Please describe.**
There are no FOSS solutions on github, which support acting as a proxy for xtream api and allow for regex based filtering of content.

**Describe the solution you'd like**
Extend this project to add a target for xtream with user and login, with filtered content

**Describe alternatives you've considered**
Several forks of https://github.com/pierre-emmanuelJ/iptv-proxy and https://github.com/alex43268/iptv-handler

**Comment by euzu** [comment]
HI, 
I dont understand the request,
it is possible to to receive and filter xtream urls. the configuration contains a username and password option.

The current implementation should fetch channels. videos and tv series, filter, map sort them as configured in the configuration.

```yaml
sources:
  - input:
      type: xtream
      headers:
        User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        Accept: application/json
        Accept-Encoding: gzip
      url: 'http://my.iptv-provider.com'
      username: myusername
      password: mysecret
```
