### ISSUE TITLE
Ability to rewrite the host part of the URL in M3U file 

### ISSUE THREAD

**Issue by adamsdavis572** [euzu/m3u-filter#17]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use m3u-filte to be able to rewrite the host names of the endpoints in the m3u file or the response from the api so that i can proxy the connection though a local proxy. I can achieve this now using m3u-filter to rewrite a file and iptv-proxy to expose the file but i would like to use xteam and your multiple playlist feature as well and i cannot see how this would be possible.  

**Describe the solution you'd like**
I would like m3u-filter to offer a feature to rewrite the host part of the endpoints in the m3u filer / api response

**Comment by adamsdavis572** [comment]
I would like to add that for each m3u xtream playlist id like to have different host names so i can route traffic to the proxies differently. This would allow me to create a playlist that can user the local address of my proxy but also route it externally via a different playlist.

**Comment by euzu** [comment]
Hi, can you please give me an example what you want to do ? 

As i understood for m3u , you have an entry like 
```
#EXTINF:-1 tvg-id="" tvg-name="One HD" group-title="GB | One",Public HD
http://my.iptv.provider.com:8080/myuser/token/streamid
```
and you want to change it to 
```
http://one.two.three.tv/myuser/token/streamid
```

in xtream it would be the direct_source  property ?

Is this what you want to do ?

**Comment by euzu** [comment]
This is currently only possible if you want to change the host parts of all entries from a `target`.
Each target  has a `rename` block.
``ỳml

   rename:
      - { field: url,  pattern: '(https?:\/\/.*?)\/(.*)',  new_name: http://my.bubble-gum.tv/$2 }
```

When you write this,  each entry of  a target will be replaced.

I will also add this to the mapping part, to more fine grained replacements,  for example each group could be have different hosts.

And what are you missing in `m3u-filter` for serving xtream and m3u-files  with password and username ?

**Comment by euzu** [comment]
Ok, i looked into the code and i saw that the url part wasnt implemented :(  I will fix this.

**Comment by euzu** [comment]
@adamsdavis572 could you test it ? Can we close the issue ?

My question about `iptv-proxy`, what functionality are you missing in `m3u-filter` ?

**Comment by euzu** [comment]
@adamsdavis572 this isnt a build issue, it is a config issue. The config format has changed.
look at line 32 in your `config.yml`

`input` configuration has changed. input is now a list. 

```yaml
sources:
  inputs:
    - enabled: true
      type: xtream
      headers:
        User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        Accept: application/json
        Accept-Encoding: gzip
      url: 'http://localhost:8080'
      username: test
      password: test
  targets:
    - name: pl1
      publish: true
      filename: playlist_1.m3u
      type: m3u
      filter: '!ALL_CHAN!'

```

**Comment by adamsdavis572** [comment]
So this is the config yml i have been using and im still getting the error

```
api: { host: 127.0.0.1, port: 8901, web_root: /home/m3u-filter/web }
threads: 0
working_dir: /home/m3u-filter/data
# sec  min   hour   day of month   month   day of week   year
schedule: "0  0  8,12,16,20,22,1  *  *  *  *"
sources:
  inputs:
    - enabled: true
      type: xtream
      headers:
        User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        Accept: application/json
        Accept-Encoding: gzip
      url: 'http://localhost:8080'
      username: test
      password: test
  targets:
    - name: pl1
      publish: true
      filename: playlist_1.m3u
      type: m3u
      filter: '!ALL_CHAN!'
``` 

However i'm still getting the same error 
`ERROR m3u_filter] M3uFilter error: cant read config file: sources: invalid type: map, expected a sequence at line 7 column 3`

I really hope im not doing something stupid here but the inputs appear to be a list to me?

**Comment by euzu** [comment]
Oh sorry,  it is my failure,    sources is a list too,

```yml

sources:
  - inputs:   <-------------  he list dash
    targets:
```

**Comment by adamsdavis572** [comment]
Thanks - that worked - ill test properly night :-)

**Comment by euzu** [comment]
> Thanks - that worked - ill test properly night :-)

Ok, i am waiting for your response

**Comment by adamsdavis572** [comment]
so i have tested the rename rule and it works exactly as needed - many thanks. 

however i cannot get the api-proxy to work. 

i have configure `api-proxy.yml`

```
server:
  protocol: http
  ip: 0.0.0.0
  http_port: 8901
  #https_port: 443
  #rtmp_port:
  timezone: Europe/London
  message: Welcome to m3u-filter
user:
  - target: pl1
    credentials:
      - {username: home, password: xxxxxxx}
```

and `config.yml`

```
api: { host: 0.0.0.0, port: 8901, web_root: "./web" }
threads: 0
......
```
but when i hit `http://<ip-address>:8901/player_api.php?username=home&password=xxxxxxxxx` i get a 400 

```
[2023-10-24T18:47:39Z INFO  actix_web::middleware::logger] 192.168.1.21 "GET /player_api.php?username=home&password=xxxxxxx HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" 0.000069
```

but if i hit `http://<ip-address>:8901/get.php?username=home&password=xxxxxxxxx` if returns 200 and the list correctly

any suggestions? thx

**Comment by euzu** [comment]
you have defined a user for the target pl1.

Do you have  a target pl1 in the config. yml?

You can only define a user for a target.

And did it run and created the files?

**Comment by euzu** [comment]
[Output doc](https://github.com/euzu/m3u-filter#1522-output)

In the README is output described

**Comment by adamsdavis572** [comment]
yes apologies this is user error i forgot to include the xtream output. now all endpoints are working  :-) 

however i have one more issue that im not sure how to resolve. 

when i call `http://x.x.x.x:8901/player_api.php?username=home&password=<password>`

i get a successful response 

```
{"user_info":{"active_cons":0,"allowed_output_formats":["ts"],"auth":1,"created_at":1666639623,"exp_date":1729711623,"is_trial":0,"max_connections":1,"message":"Welcome to m3u-filter","password":"dfdfdf","username":"home","status":"Active"},"server_info":{"url":"x.x.x.x","port":8901,"https_port":443,"server_protocol":"http","rtmp_port":1935,"timezone":"Europe/London","timestamp_now":1698175623,"time_now":"2023-10-24 20:27:03"}}
```

however the returned `password` field seems to be hardcoded 

https://github.com/euzu/m3u-filter/blob/76e96093d3dc00fe9cef4984007c2450e78628d8/src/api/xtream_player_api.rs#L25

i assume this is not correct? 

thx

**Comment by adamsdavis572** [comment]
Additional info 
This user name and password is used in subsequent calls from the iptv client (smarters iptv) and then fails due to mismatch.

**Comment by euzu** [comment]
Ah ok,
i implemented the xtream  api  based on data i have gathered on github. I dont have an api xtream account and couldnt test it well. 

It could be that i forgot to write the right password in the response. İ will fix this tomorrow. Now its a little bit too late.

**Comment by euzu** [comment]
@adamsdavis572 i have pushed a new version, please test it.

**Comment by euzu** [comment]
@adamsdavis572 when you give me a go, i will create a new release with the new web-ui changes.

**Comment by adamsdavis572** [comment]
so `/player_api.php?username=home&password=password` now works correctly and returns the correct info - thank you 👍 

```
{"user_info":{"active_cons":0,"allowed_output_formats":["ts"],"auth":1,"created_at":1666721205,"exp_date":1729793205,"is_trial":0,"max_connections":1,"message":"Welcome to m3u-filter","password":"password","username":"home","status":"Active"},"server_info":{"url":"x.x.x.x","port":8901,"https_port":443,"server_protocol":"http","rtmp_port":1935,"timezone":"Europe/London","timestamp_now":1698257205,"time_now":"2023-10-25 19:06:45"}}
```

however the other, subsequent xtream api calls all fail with a 400 

`/player_api.php?username=home&password=password&action=get_live_categories`
`/player_api.php?username=home&password=password&action=get_vod_categories`
`/player_api.php?username=home&password=password&action=get_series_categories`

error from `/player_api.php?username=home&password=password&action=get_live_categories`

```
[2023-10-25T18:06:39Z INFO  actix_web::middleware::logger] 192.168.1.21 "GET /player_api.php?username=home&password=password&action=get_live_categories HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" 0.000144
```

**Comment by euzu** [comment]
@adamsdavis572 i will try to figure out what the problem is. It happens when you make the same api  call in short cycles ?

**Comment by adamsdavis572** [comment]
thanks - it happens when you supply any `action` as a query param. how do you provide the mapping from categories to m3u groups? is it inherited from the original xstream api call?

**Comment by euzu** [comment]
if your surce is xtream, then the categories and groups are the same.
if you source is m3u the categories are guessed based on the video.extensions  configuration.
 Everyhting that matches the  extension is categorized as Video, anything alse as Live.


I have tested the api and called it with curl, i got no 400 responses.

I try to write more debug logs to figure out what is happening at your side.

**Comment by euzu** [comment]
i have added some debug information. You need to set loglevel via command line argument

Following log levels are supported:
- `debug`
- `info` _default_
- `warn`
- `error`
 
Use the `-l` or `-log-level` cli-argument to specify the log-level.

**Comment by adamsdavis572** [comment]
ok so im still getting the same 400 and i cant see any more debug info that might give me a clue 

```
$./m3u-filter -s  -a api-proxy.yml -c config.yml -l debug
[2023-10-25T19:58:14Z DEBUG m3u_filter::filter] template ALL_CHAN  depends on [US_CHAN, UK_CHAN]
[2023-10-25T19:58:14Z DEBUG m3u_filter::filter] [
        PatternTemplate {
            name: "UK_CHAN",
            value: "Group ~ \"^.UK..*\"",
        },
        PatternTemplate {
            name: "US_CHAN",
            value: "Group ~ \"^.US..*\"",
        },
        PatternTemplate {
            name: "ALL_CHAN",
            value: "Group ~ \"^.US..*\" OR Group ~ \"^.UK..*\"",
        },
    ]
[2023-10-25T19:58:14Z DEBUG m3u_filter::filter] Created regex: ^.US..* with captures: []
[2023-10-25T19:58:14Z DEBUG m3u_filter::filter] Created regex: ^.UK..* with captures: []
[2023-10-25T19:58:14Z DEBUG m3u_filter::model::config] Filter: Group ~ "^.US..*" OR Group ~ "^.UK..*"
[2023-10-25T19:58:14Z DEBUG m3u_filter::filter] Created regex: ^.US..* with captures: []
[2023-10-25T19:58:14Z DEBUG m3u_filter::filter] Created regex: ^.UK..* with captures: []
[2023-10-25T19:58:14Z DEBUG m3u_filter::model::config] Filter: Group ~ "^.US..*" OR Group ~ "^.UK..*"
[2023-10-25T19:58:14Z INFO  m3u_filter] working dir: "/home/xxxx/git/m3u-filter/scratch/data"
[2023-10-25T19:58:14Z WARN  m3u_filter::config_reader] cant read mapping file: ./mapping.yml
[2023-10-25T19:58:14Z DEBUG m3u_filter::config_reader] no mapping loaded
[2023-10-25T19:58:14Z DEBUG m3u_filter] web_root: /home/xxxx/git/m3u-filter/scratch/web
[2023-10-25T19:58:14Z INFO  m3u_filter] server running: http://0.0.0.0:8901
[2023-10-25T19:58:14Z INFO  actix_server::builder] starting 2 workers
[2023-10-25T19:58:14Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[2023-10-25T19:58:45Z INFO  actix_web::middleware::logger] 192.168.1.xx "GET /player_api.php?username=home&password=password&action=get_live_categories HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" 0.000114
[2023-10-25T19:58:46Z INFO  actix_web::middleware::logger] 192.168.1.xx "GET /player_api.php?username=home&password=password&action=get_live_categories HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" 0.000067
```

here is the config file im using 

```
api: { host: 0.0.0.0, port: 8901, web_root: ./web }
threads: 0
working_dir: ./data
templates:
  - name: UK_CHAN
    value: Group ~ "^.UK..*"
  - name: US_CHAN
    value: Group ~ "^.US..*"
  - name: ALL_CHAN
    value: >-
      !US_CHAN! OR
      !UK_CHAN!
sources:
  - inputs:
    - enabled: true
      type: xtream
      headers:
        User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        Accept: application/json
        Accept-Encoding: gzip
      url: 'http://myportal.live:8080'
      username: Qf9GFSBeu8Up
      password: Qngq4aNjtaVt
    targets:
      - name: pl1
        output:
          - type: xtream
        rename:
          - { field: url,  pattern: '(https?:\/\/.*?)\/(.*)',  new_name: "http://192.168.1.xxxx:8901/$2" }
        sort:
          groups:
            order: asc
        filter: "!ALL_CHAN!"
      - name: pl2
        output:
          - type: xtream
        rename:
          - { field: url,  pattern: '(https?:\/\/.*?)\/(.*)',  new_name: "https://iptvproxy.xxxxx.net/$2" }
        sort:
          groups:
            order: asc
        filter: "!ALL_CHAN!"
```
