### ISSUE TITLE
EPG response empty

### ISSUE THREAD

**Issue by adamsdavis572** [euzu/m3u-filter#176]
Following an upgrade from 2.0.5 to 2.2.1, i needed to make some changes to config files but now reverse proxy mode is working correctly however EPG is not working. Im i missing something from the new config? thanks in advance.
 
**To Reproduce**

`https://host:port/xmltv.php?username=name&password=password`

returns 

`<?xml version="1.0" encoding="utf-8" ?><!DOCTYPE tv SYSTEM "xmltv.dtd"><tv generator-info-name="Xtream Codes" generator-info-url=""></tv>`

**Expected behavior**
EPG returned 

**config**

```
  targets:
    - name: pl1
      output:
        - type: xtream
      filter: "!ALL_CHAN!"
      options: {ignore_logo: false, xtream_skip_live_direct_source: true, xtream_skip_video_direct_source: true}
      sort:
        match_as_ascii: true
        groups:
          order: asc
```

**Comment by euzu** [comment]
hi @adamsdavis572   
i have tested it now and the epg works.  What i do is to enable the epg configuration

```yaml
sources:
- inputs:
  - name: all_channels
    type: xtream
    username: xyz
    password: secret
    url: http://provider-host
    epg_url: http://provider-host/xmltv.php?username=xyz&password=secret
```

After running an update the epg xml is available under  `http://m3u-filter-host:port/xmltv.php?username=abcd&password=abcd.secret`


From 2.05 to 2.2.1 is a big upgrade, the file structure for the db files has changed, you need to empty the data folder to avoid wrong format exceptions.
