### ISSUE TITLE
New Feature for Targets for xtreme is documented incorrectly

### ISSUE THREAD

**Issue by iceman73** [euzu/m3u-filter#188]
The Example shows "," needed in skip options, but it errors with it in.

```
targets:
  - name: xc_m3u
    output:
      - type: xtream
        skip_live_direct_source: true,
        skip_video_direct_source: true,
```

It should be as follows:

```
targets:
  - name: xc_m3u
    output:
      - type: xtream
        skip_live_direct_source: true
        skip_video_direct_source: true
```
