### ISSUE TITLE
Web UI doesn't work behind a reverse proxy with a path prefix

### ISSUE THREAD

**Issue by jbergler** [euzu/m3u-filter#193]
**Describe the bug**
The WebUI serves an index.html file with references to css + js files at `/static/...` regardless of the api-proxy configuration. 

**To Reproduce**
```yaml
server:
  - name: extern
    protocol: https
    host: example.com
    port: 443
    rtmp_port:
    timezone: Etc/UTC
    message: Welcome to m3u-filter
    path: /some-prefix
```

Configure proxy (in my case traefik) and try to load the WebUI.

**Expected behavior**
The UI renders.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: firefox
 - Version: 136

**Additional context**
It's not clear to me that this is expected to work.
It looks like the build process for the container builds the frontend with [PUBLIC_URL empty](https://github.com/euzu/m3u-filter/blob/87134a19342d0af2aff9b1addf3e185b92bb59d1/frontend/package.json#L14)

If this is out of scope for what you had imagined, please feel more than free to just close this.
Thanks for reading, and for all the work on this project.

**Comment by jbergler** [comment]
I did suspect that this wasn't the intended use of the `path` setting (and not a big deal if you don't want to solve for this)

It would be nice to also allow the UI to work behind a reverse-proxy.
In your nginx example you could use `sub_filter` to rewrite the response body, but most proxies don't support an equivalent.

**Comment by euzu** [comment]
@jbergler i have added `web_ui_path` to  `config.yml`. Can you test it please.

I have pushed to master and pushed a x86_64 beta docker image.

**Comment by jbergler** [comment]
Awesome, all my infra is aarch64 - any chance it's easy for you to push that? If not I'll build myself and test.

**Comment by euzu** [comment]
i have pushed aarch64-beta image. can you test it .

**Comment by jbergler** [comment]
Definitely making some progress

I have in `api_proxy.yaml`

```yaml
server:
  - name: extern
    protocol: https
    host: example.com
    port: 443
    path: /m3u/data
```

And in `config.yaml`
```yaml
web_ui_path: /m3u/ui
```

I've configured traefik to rewrite the request for `/m3u/data/(.*)` so they come through as `/$1`
While `/m3u/ui` is not rewritten.

The login page renders, but fails because `config.json` doesn't have the prefix in it for the server url.
```json
{"api":{"serverUrl":"/api/v1/"},"app_logo":null,"app_title":"m3u-filter"}
```
