### ISSUE TITLE
Buffering/Lagging for 1080p 50FPS content | Reverse Proxy Mode (Latest version 2.2.5)

### ISSUE THREAD

**Issue by solohpgh** [euzu/m3u-filter#198]
**Describe the bug**
The most recent iterations of M3U-FILTER (not exactly sure from when), has introduced some type of overhead in reverse proxy mode, when playing FHD/1080p - 50FPS, UHD/4K - 30FPS content.  

IPTV clients tested include (Tivimate/Sparkle/Smarters/UHF), all experience buffering.

My testing so far, shows me that content up to FHD/1080p 25FPS, plays smoothly in reverse proxy mode, anything more will exhibit buffering in the client.

**To Reproduce**
Play content 1080p (or higher), running at 50FPS (or higher) / 4K/UHD, running at 30FPS (or higher)

**Expected behaviour**
Buffering or pausing, for the duration of playback every 5-10 seconds

**Smartphone (please complete the following information):**
 - Google Chromecast 4K (latest software) | Tivimate & Sparkle
 - Amazon Firestick 4K Max (latest software) | Tivimate, Sparkle & Smarters
 - Apple TV 4K, Gen1 (latest software) | UHF
 - iPhone 15 (latest software) | UHF

**Additional context**
I can play the content in redirected mode or direct from the source in the client, and no buffering is experienced.

**_Using previous versions of M3U-FILTER, currently testing with 2.0.5, experiences no buffering in reverse proxy mode while playing the content described in this post._**

Other things to note:
- Using latest version with or without VPN, in reverse proxy mode, buffering is experienced.
- Using latest version, increased the stream buffer size in config.yml, buffering is experienced.
- Using latest version, disabled the stream buffer in config.yml, buffering is experienced.
- Using the source directly in the client with or without VPN, **no** buffering is experiences.

**Comment by solohpgh** [comment]
```
threads: 0
api:
  host: 0.0.0.0
  port: 8999
  web_root: /web
update_on_boot: false
web_ui_enabled: true
working_dir: /data
backup_dir: ./backup
video:
  extensions:
  - mkv
  - avi
  - mp4
  download:
    headers: {}
    organize_into_directories: false
schedules:
- schedule: 0  27  2,10,18  *  *  *  *
  targets: []
messaging:
  notify_on: []
log:
  sanitize_sensitive_info: false
  active_clients: true
  log_level: info
#custom_stream_response:
#  channel_unavailable: ./resources/channel_unavailable.ts
#  user_connections_exhausted: ./resources/user_connections_exhausted.ts
#  provider_connections_exhausted: ./resources/provider_connections_exhausted.ts
connect_timeout_secs: 3
reverse_proxy:
  stream:
#    throttle_kbps: 49152
    retry: false
    buffer:
      enabled: true
      size: 2048
  cache:
    enabled: true
    size: 50MB
    dir: /data/cache
  resource_rewrite_disabled: false

```
