### ISSUE TITLE
Export as `.strm` files tree

### ISSUE THREAD

**Issue by kumy** [euzu/m3u-filter#2]
**Is your feature request related to a problem? Please describe.**
Filter part of an m3u and export to .strm files.

**Describe the solution you'd like**
Instead of exporting to other(s) m3u file(s), create a folder per Group and a file per Title. The file contain the media url. Having the ability to map usual Group/Name/Title to file path pattern (and using regex) would be a big plus.

**Describe alternatives you've considered**
Found those projects, didn't tested them yet:
- https://github.com/ggiraudon/m3u2strm
- https://github.com/trix7777/m2strm
- https://github.com/erdesigns-eu/M3U2STRM
- https://github.com/silence48/m3u2strm

**Additional context**
This well explain it https://forums.nextpvr.com/showthread.php?tid=62393.

**strm details**
https://kodi.wiki/view/Internet_video_and_audio_streams
> These are basic text files that look like <name>.strm and contain a URL to the internet stream.

**Comment by euzu** [comment]
We can solve this with target types. Depending on which type is specified, the result will be output accordingly.
Depending on the type, filename should then be a directory or an actual file.

**Comment by kumy** [comment]
That would be awesome! What would the conf look like?

**Comment by euzu** [comment]
i think something like this:
 targets:
      - type: m3u
        filename: playlist_1.m3u
        filter: (Group ~ "^DE\s.*" AND Title ~ "^DE\s.*")
        options: { ignore_logo: true }
        rename:
          - { field: Group, new_name: 1. DE$1, pattern: ^DE(.*) }
        sort: { order: Asc }
      - type: strm
        filename: strm_files
        filter: (Group ~ "^DE\s.*")
        options: { ignore_logo: true }
        rename:
          - { field: Group, new_name: 1_DE$1, pattern: ^DE(.*) }

btw: i am working on your other request, the filter is now a  string  like:
(Field ~ regexp) AND (Field ~ Regexp) OR (NOT Field ~ Regexp)

**Comment by kumy** [comment]
`(Field ~ regexp) AND (Field ~ Regexp) OR (NOT Field ~ Regexp)`
Neat!

Would like you a dedicated issue for the second part in https://github.com/euzu/m3u-filter/issues/1#issuecomment-1085017112?

**Comment by euzu** [comment]
There are two types of targets ```m3u``` and ```strm```. This can be set by the ```output``` attribute to ```Strm``` or ```M3u```. 
If the attribute is not specified ```M3u``` is created by default.

```Strm``` output has an additional option ```underscore_whitespace```. This replaces all whitespaces with ```_``` in the path.

config looks like:
```yaml
api: { host: 127.0.0.1, port: 8901, web_root: /home/m3u-filter/web }
working_dir: /home/m3u-filter/data
sources:
  - input: { persist: 'playlist_1_{}.m3u', url: 'http://myserver.net/playlist.m3u' }
    targets:
      - filename: playlist_strm
        type: Strm
        filter: 'Group ~ "^DE\s.*" OR Group ~ "TR\s.*"'
        options: { ignore_logo: true, underscore_whitespace: true }
        rename:
          - { field: Group, new_name: 1. DE$1, pattern: ^DE(.*) }
        sort: { order: Asc }
```

**Comment by euzu** [comment]
If desired, I could add another option ```cleanup: true|false``` that deletes the old directory first for strm files.

**Comment by kumy** [comment]
Seem perfect!! You rocks!

Will try it this evening.
Effectively, a `cleanup` would make sense

**Comment by kumy** [comment]
I'm not able to have the `cleanup` working. I'm using `0.9.2`.
Part of my conf:
```
      - filename: vod/vod/series/
        type: Strm
        cleanup: true
        filter: 'Group ~ "^\|FR\|\s+" AND Url ~ "/series/"'
        options: {ignore_logo: true}
        rename:
          - {field: Group, new_name: $1, pattern: ^.*\|\s(.*)(\s\(.*)?}
          - {field: Title, new_name: $1, pattern: ^\s?(.*)}
        sort: {order: Asc}
```
I have some files in `vod/vod/series/ULTRA\ HD\ 4K/` that remain after update.

BTW, `--version` report the wrong version
```
$ ./m3u-filter_v0.9.2_linux_x86_64/m3u-filter --version
m3u-filter 0.5.0

```

**Comment by euzu** [comment]
cleanup belongs to the options section.
```yaml
options:
      ignore_logo: true
      underscore_whitespace: true
      cleanup: true
```
