### ISSUE TITLE
Mapper does not assign chno attribute

### ISSUE THREAD

**Issue by andresjocrack** [euzu/m3u-filter#200]
The mapper does not set the chno attribute. Other fields are correctly set, but chno is not assigned (Or maybe it is overwriten at a later stage?). This used to work as I expected until 2.0.10, not sure if it is a bug or an intended behaviour change (I have checked documentation and does not seem to be the case).

I prepared a simplified mapping to isolate the problem, to ensure it was not a problem with the mapping not getting executed. 

1. Create a mapping like this:

```
    - id: 000_set_default_channel_number_best_tv
      mapper:
        - pattern: Name ~ ".*"
          attributes:
            title: XXX
            chno: 1000

```

Use it in the source file for the corresponding target

      - name: best_iptv
        output:
          - type: m3u
            filename: /backup/best_iptv_backup.m3u
        processing_order: frm
        filter: '!BEST_ALL_FILTERS!'
        mapping:
          - 000_set_default_channel_number_best_tv
        options:
          ignore_logo: false
        rename:
          - field: name
            pattern: ^(.+?)\s+(HD 1080P|HD 720P|FHD|HD|SD).*$
            new_name: $1 $2

I would expect that all channels are set as title XXX and chno 1000, but all entries  show as follows (Anonimized):

`#EXTINF:-1 tvg-id="MYCHANNEL" tvg-name="MYCHANNEL" group-title="MYGROUP" tvg-logo="MYCHANNEL.png" tvg-chno="47",XXX
`
This shows the mapping is getting executed but the chno field seems to be ignored
