### ISSUE TITLE
Allow Custom Group Order with Regex

### ISSUE THREAD

**Issue by g0ldyy** [euzu/m3u-filter#207]
**Is your feature request related to a problem? Please describe.**
It is currently impossible to choose the order of groups with regexes without renaming them, which is an ugly way of doing this.

**Describe the solution you'd like**
A new key under `sort.groups` could be added, for example, `order_list`, which would contain a list of regex or exact group names in the desired order. Groups matching the first patterns in the list would appear first.

Example:
```yml
    targets:
      - name: some_target
        output:
          - type: 'xtream'
          - type: 'm3u'
        filter: '!SOME_FILTER!'
        options: {ignore_logo: false, share_live_streams: false, remove_duplicates: true}
        sort:
          groups:
            order_list:
              - '.*SD.*'
              - '.*HD.*'
              - '.*FHD.*'
              - '.*4K.*'
              - '.*REGIONS.*'
              - '.*SPORTS.*'
              - '.*WORLD SPORTS.*'
              - '.*ENTERTAINMENT.*'
              - '.*KIDS.*'
              - '.*PLUTO TV.*'
              - '.*TF1\+.*'
              - '.*RADIOS.*'
            # optional: how to sort groups not listed above
            # 'append' (default): adds them at the end
            # 'prepend': adds them at the beginning
            # 'ignore': removes them
            unmatched_order: append
            # optional: alphabetical sort for unlisted groups
            unmatched_sort: asc # or 'desc'.
```

**Describe alternatives you've considered**
X

**Additional context**
X

**Comment by euzu** [comment]
`# 'ignore': removes them`  does not work, because sort is not a filter, this can be done by filtering.

do we need `unmatched_order`  or `unmarched_sort`, because we have  `order`  and  order is applied to all unmatched,.

And the given order_list should be at the start ?

**Comment by euzu** [comment]
Added support for regular expression-based sequence sorting.
  You can now sort both groups and channels using custom regex sequences.
```yaml
sort:
  groups:
  order: asc
  sequence:
  - '^Freetv'
  - '^Shopping'
  - '^Entertainment'
  - '^Sunrise'
  channels:
  - field: caption
    group_pattern: '^Freetv'
    order: asc
    sequence:
    - '(?P<c1>.*?)\bUHD\b'
    - '(?P<c1>.*?)\bFHD\b'
    - '(?P<c1>.*?)\bHD\b'
    - '(?P<c1>.*?)\bSD\b'
```
In the example above, groups are sorted based on the specified sequence.
Channels within the `Freetv` group are first sorted by `quality` (as matched by the regex sequence), and then by the `captured prefix`.

To sort by specific parts of the content, use named capture groups such as `c1`, `c2`, `c3`, etc.
The numeric suffix indicates the priority: `c1` is evaluated first, followed by `c2`, and so on.
