### ISSUE TITLE
xmltv endpoint returning error on Rel 1.1.1

### ISSUE THREAD

**Issue by adamsdavis572** [euzu/m3u-filter#21]
**Describe the bug**
I am testing the `xmltv` with the api-proxy and im getting an error. I understand that `xmltv` is implemented now? 

**To Reproduce**

call to `xmltv.php?username=xxxx&password=xxxx`

gets this response in `iptv-proxy`

```
[GIN] 2023/11/01 - 20:04:03 | 500 |    2.679025ms |    172.29.20.12 | GET      "/xmltv.php?username=xxxx&password=xxxx"
Error #01: status code was 400, expected 2XX-3XX```
```

Logs in m3u-filter
```
[2023-11-01T20:04:07Z INFO  actix_web::middleware::logger] 172.29.20.9 "GET /xmltv.php?username=XXXX&password=XXXX&action=xmltv.php HTTP/1.1" 400 0 "-" "Dalvik/2.1.0 (Linux; U; Android 13; SM-S906B Build/TP1A.220624.014)" 0.000178
```

**Comment by euzu** [comment]
400 means no files available.
1) your input definition needs epg_url
2) The update should run after updating the config.  you can run in cli mode or start update with web ui

**Comment by euzu** [comment]
I have now changed the HTTP Response to 404 NoContent instead of BadRequest if no files are available.

**Comment by adamsdavis572** [comment]
@euzu thanks for the response, ive added epg_url to my sources and i now have an epg file in `/data` however im still getting 204 response.  

```
sources:
  - inputs:
    - enabled: true
      type: xtream
      persist: playlist_1_{}.m3u
      headers:
        User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        Accept: application/json
        Accept-Encoding: gzip
      url: 'http://xxxx.xxxx:8080'
      epg_url: 'http://xxxx.xxxx:8080/xmltv.php'
      username: xxxx
      password: xxxx
```

`[2023-11-02T10:50:02Z INFO  actix_web::middleware::logger] 192.168.1.21 "GET /xmltv.php?username=xxxx&password=xxxx HTTP/1.1" 204 0 "-" "curl/7.85.0" 0.000159`

Any suggestions here? 

thanks

**Comment by euzu** [comment]
@adamsdavis572   `persist` should be different for `m3u` and `xtream` types. For `m3u` use full filename like `./playlist_{}.m3u`. For `xtream` use a prefix like `./playlist_`. 

What for `target('s)` do you have ?.  `xtream`output creates a folder with the `target name`. The `epg.xml` file should be inside this folder.:  `./data/<target_name>/epg.xml`.

Can you check the file ?  IF there is a file and you get NoContent, then i have to add some debug outputs to find out the problem.

**Comment by euzu** [comment]
@adamsdavis572 i have added 2 debug outputs to xmltv api, it prints the expected filename if not found.

**Comment by adamsdavis572** [comment]
so this is the output 
```
[2023-11-02T22:00:53Z INFO  m3u_filter::api::xmltv_api] Cant find epg file for xtream target: /data/pl1/epg.xml
[2023-11-02T22:00:53Z INFO  m3u_filter::api::xmltv_api] Cant find epg file for m3u target: /data/epg_playlist_1.xml
[2023-11-02T22:00:53Z INFO  actix_web::middleware::logger] 172.29.20.9 "GET /xmltv.php?username=xxxx&password=xxxx&action=xmltv.php HTTP/1.1" 204 0 "-" "Dalvik/2.1.0 (Linux; U; Android 13; SM-S906B Build/TP1A.220624.014)" 0.000188
```

i have no epg.xml i'm my playlist (pl1) directory

and this is the config - am i missing something in `targets`? i dont see anything in the documents
```
sources:
  - inputs:
    - enabled: true
      type: xtream
      persist: playlist_1_
      headers:
        User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        Accept: application/json
        Accept-Encoding: gzip
      url: 'http://xxxx.xxxx:8080'
      epg_url: 'http://xxxx.xxxx:8080/xmltv.php?username=xxxx&password=xxxx'
      username: xxxx
      password: xxxx
    targets:
      - name: pl1
        output:
          - type: xtream
          - type: m3u
            filename: playlist_1.m3u
        sort:
          groups:
            order: asc
        filter: "!ALL_CHAN!"
```

thanks
