### ISSUE TITLE
Support env flags everywhere

### ISSUE THREAD

**Issue by net0-dev** [euzu/m3u-filter#215]
The inputs configs often have sensitive information like xtream user/password. You have added support for `${env:SOMETHING}` in the api-proxy.yml but not in source.yml. 

I imagine this is simple enough given you've already done it elsewhere :) 

Thanks for your hard work!

```yaml
sources:
  - inputs:
      - 
        name: mysecretprovider
        enabled: true
        type: xtream
        persist: 'live_stream_1_{}.m3u'
        epg_url: file:///data/epg/guide.xml
        url: ${env:IPTV_SOURCE_HOST}
        username: ${env:IPTV_SOURCE_USER}
        password: ${env:IPTV_SOURCE_PASS}
```
