### ISSUE TITLE
Unable to launch docker image

### ISSUE THREAD

**Issue by foux** [euzu/m3u-filter#242]
Hello!

I'm trying to start m3u-filter with docker using pre-build image.
The part of my compose-file regarding m3u-filter is like this : 
```
  m3u-filter:
    container_name: m3u-filter
    image: ghcr.io/euzu/m3u-filter:latest
    user: "1000:200"
    working_dir: /app
    volumes:
      - ./m3u-filter/config:/app/config
      - ./m3u-filter/data:/app/data
      - ./m3u-filter/backup:/app/backup
      - ./m3u-filter/downloads:/app/downloads
    environment:
      - TZ=Europe/Paris
    ports:
      - "8901:8901"
    networks:
      - medias
    restart: unless-stopped
```

But launching the image, I get this error :  `Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./m3u-filter": stat ./m3u-filter: no such file or directory: unknown`

Anybody has an idea how to fix this?
Thanks
