### ISSUE TITLE
when persisting epg xml when using xtream in reverse mode only the first "programme" entry is persisted 

### ISSUE THREAD

**Issue by adamsdavis572** [euzu/m3u-filter#29]
**Describe the bug**
when using "epg_url" in "xtream" configuration, the epg.xml created under the playlist directory only contains a single "program" entry per channel.  However the epg should have many programme entires per channel. For example the epg.xml contains only a single program entry for "bbc1.uk"

```
<programme channel="bbc1.uk" start="20231206224000 +0000" stop="20231207001000 +0000">
  <title>Match of the Day</title>
  <desc>Highlights of the midweek Premier League games, including Manchester United against Chelsea at Old Trafford and Manchester City's trip to Aston Villa. [S] [HD.</desc>
</programme>
``` 

However in `epg_playlist_1_.xml` the are 57 programme entries and the first is the entry above. Is it possible that the code is stopping after 1 programme entry per channel when filtering?  

This is my configuration for source.xml

```
sources:
- inputs:
    - type: xtream
      persist: playlist_1_
      url: 'http://<iptv-provider>:8080'
      epg_url: http://<iptv-provider>/xmltv.php?username=username&password=password
      username: username
      password: password
      options: {xtream_info_cache: true, }
  targets:
    - name: pl1
      filename:
      filter: "!ALL_CHAN!"
      output:
        - type: xtream
      sort:
        match_as_ascii: true
        groups:
          order: asc
```

**Expected behavior**
All programme entries for a channel is available in the filtered epg.xml
