### ISSUE TITLE
Seperate the config path

### ISSUE THREAD

**Issue by haroldthegray** [euzu/m3u-filter#35]
**Is your feature request related to a problem? Please describe.**
I am unable to leverage an idempotent container of the software due to the lack of a separate/sub path for persistence files. 

**Describe the solution you'd like**
Instead of [copying configuration at container build](https://github.com/euzu/m3u-filter/blob/d65ddbd19f2417797070a4be2a5c938b2c7de011/docker/Dockerfile#L10), have a dedicated config folder that is mountable [similar to the data directory](https://github.com/euzu/m3u-filter/blob/d65ddbd19f2417797070a4be2a5c938b2c7de011/docker/docker-compose.yml#L8).

**Describe alternatives you've considered**
Self-building with own config files for each release is not efficient and it doesn't make the container shareable.

**Additional context**
Making this change to the software would also enable the build to be uploaded to the Docker Registry as requested in #34. Users could put their config in the designated location on the host and we could all just pull from docker registry when a new version is released.

This will help your container be more idempotent and encourage your users to stay updated with changes.

**Comment by euzu** [comment]
@haroldthegray  the config paths can be given through parameter, the docker cmd could be include all  config file paths  in a directory which could be mounted.

But i can add an extra config path option where all config files should be found.

But i dont understand the problem about persisted files. The  directory can be configured.

**Comment by euzu** [comment]
@haroldthegray does the release v1.1.8 fit your needs ?

**Comment by euzu** [comment]
@haroldthegray i have published a docker image

```sh
docker pull ghcr.io/euzu/m3u-filter:latest
```

my example docker-compose:

```yaml
version: '3'
services:
  m3u-filter:
    container_name: m3u-filter
    image: ghcr.io/euzu/m3u-filter:latest
    user: "133:144"
    working_dir: /
    volumes:
      - /opt/m3u-filter/config:/config
      - /opt/m3u-filter/data:/data
      - /opt/m3u-filter/.backup:/backup
      - /share/m3u-filter:/downloads
    environment:
      - TZ=Europe/Paris
    ports:
      - "8901:8901"
    restart: unless-stopped
```
