### ISSUE TITLE
Empty `persist` value, still persist the file with filename `~`

### ISSUE THREAD

**Issue by kumy** [euzu/m3u-filter#4]
Empty `persist` value in config, still persist the file with filename `~`.

**To Reproduce**
1. Change a valid `config.yml`, and set the `persist` to nothing
```yaml
sources:
  - input:
      url: 'file.m3u'
      persist:
```
2. Run the command in verbose
```
working dir: "/srv/IPTV/m3u"
persist file: Some("/srv/IPTV/m3u/~")
```
3. check directory content
```shell
$ ls -l /srv/IPTV/m3u/
drwxrwxr-x 2 xxx xxx     4096 Jan 12 22:28  ./
drwxr-xr-x 4 xxx xxx     4096 Jan 12 22:28  ../
-rw-rw-r-- 1 xxx xxx    27011 Jan 12 22:28 '~'
```

**Expected behavior**
No file should be created at all.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser N/A
 - Version 22.04

**Additional context**

with "empty string" the behavior is the expected one
```yaml
sources:
  - input:
      url: "file.m3u"
      persist: ""
```

```shell
working dir: "/srv/IPTV/m3u"
persist file: None
```
no file is created
