### ISSUE TITLE
The wrong upstream is used for xtream

### ISSUE THREAD

**Issue by RohirrimRider** [euzu/m3u-filter#44]
**Describe the bug**
I have two inputs for a single output. One of the inputs is LIVE_PROVIDER and the other is VOD_PROVIDER. The VOD PROVIDER has VOD streams. It seems that when I open any link it always defaults to the first provider, even if the stream came from the second provider. 

**To Reproduce**
1. Add two xtream inputs
2. Open any of the streams provided by the second xtream provider
3. You get a 302 redirect to the wrong upstream provider and a `406 Not Acceptable` because that's not the right URL.

**Expected behavior**
The stream link should remember which upstream from which it originated.

Here is my config stripped of passwords and domains. All streams go to MAIN_PROVIDER.

```
---
sources:
  - inputs:
      - enabled: true
        type: xtream
        persist: 'playlist_1_1{}.m3u'
        headers:
          User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        url: 'http://MAIN_PROVIDER.com:826'
        username: *****
        password: *****
        options:
          xtream_info_cache: true

      - enabled: true
        type: xtream
        persist: 'vod_{}.m3u'
        headers:
          User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        url: 'https://SECOND_PROVIDER.xyz'
        username: *****
        password: *****
        options:
          xtream_info_cache: true
    targets:
      - name: pl1
        output:
          - type: xtream
        options:
          xtream_skip_live_direct_source: true
          xtream_skip_video_direct_source: true
        filter: >-
          (!ALL_CHANNELS!) OR (!Locals!) OR (!VOD!)
        mapping:
          - espn
          - 24/7
          - locals
          - NetworkTv
          - sports
        sort:
          groups:
            order: asc

```

**Comment by euzu** [comment]
@RohirrimRider this is a known issue which was reported by @haroldthegray. I am working on it. First solution did not work.

**Comment by RohirrimRider** [comment]
Along the same lines it would be nice if we could set type filters on inputs. Between those two inputs I only want VOD from one of them. Something like this:

```
      - enabled: true
        type: xtream
        persist: 'vod_{}.m3u'
        headers:
          User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
        url: 'https://SECOND_PROVIDER.xyz'
        username: *****
        password: *****
        options:
          xtream_info_cache: true
          types:
            - vod
            - live
```

**Comment by euzu** [comment]
[Feature request for input filter](https://github.com/euzu/m3u-filter/issues/45)

**Comment by RohirrimRider** [comment]
@euzu any luck?

**Comment by euzu** [comment]
You can set options for input.

```yaml
     - enabled: true
        type: xtream
        url: 'https://second_provider.xyz/'
        username: *****
        password: *****
        options: 
          - xtream_info_cache: true
          - xtream_skip_series: true
          - xtream_skip_vod: true
          - xtream_skip_live: true
```

Changes are in master branch
