### ISSUE TITLE
Filter xtream cluster

### ISSUE THREAD

**Issue by euzu** [euzu/m3u-filter#45]
**Is your feature request related to a problem? Please describe.**
I want to set a xtream cluster filter for live, vod, and series for input.

**Describe the solution you'd like**

Input config like

```yaml
      - enabled: true
        type: xtream
        url: 'https://second_provider.xyz/'
        username: *****
        password: *****
        options:
          xtream_info_cache: true
          types:
            - vod
            - live
```

**Comment by euzu** [comment]
You can now skip xtream sections with options:

```yaml
      - enabled: true
        type: xtream
        url: 'https://second_provider.xyz/'
        username: *****
        password: *****
        options: 
          - xtream_info_cache: true
          - xtream_skip_series: true
          - xtream_skip_vod: true
          - xtream_skip_live: true
```
