### ISSUE TITLE
Reverse proxy is not rewriting urls

### ISSUE THREAD

**Issue by RohirrimRider** [euzu/m3u-filter#47]
**Describe the bug**
Using `reverse` for proxy does not rewrite urls for proxying

```
server:
  - name: default
    protocol: http
    host: xtream.myhost.com
    http_port: 0
    https_port: 443
    rtmp_port: 0
    timezone: America/Chicago
    message: Welcome to m3u-filter

user:
  - target: pl1
    credentials:
      - username: myuser
        password: mypassword
        proxy: reverse
```

and then 

```
curl https://xtream.myhost.com/m3u?username=myuser&password=mypassword
```

URLs are upstream urls. I expect them to be https://xtream.myhost.com. Is that the intent of reverse proxy?
