### ISSUE TITLE
Mapping capture groups usable in the tag

### ISSUE THREAD

**Issue by euzu** [euzu/m3u-filter#5]
**Is your feature request related to a problem? Please describe.**
Capture variables defined in the mapping regular exrpressions, should be usable for the tag.
The tag should be configurable for multiple variables, a suffix, a prefix and a concatenator.

**Describe the solution you'd like**
The tag definitions should be:
```yaml
    tag: 
      captures:
         - quality
      prefix: ' ['
      suffix: ']'
      concat: '|'
```
`concat` is only If you have multiple capture variables.
`captures`  should be a list of variables names used in the regular expressions for mapping.

Example:

`^\s*(FR)?[: |]?TF1!delimiter!!quality!\s*$`

**Comment by euzu** [comment]
@kumy: please check the new functionality. i have pushed the changes.,

this is an example mappings.yaml file:

Please consider the change of `templates.key` attribute to `templates.name`

```
mappings:
  - id: France
    tag: 
      captures:
         - quality
      prefix: ' ['
      suffix: ']'
    match_as_ascii: true
    templates:
      - name: delimiter
        value: '[\s_-]*'
      - name: quality
        value: '(?i)(?P<quality>HD|LQ|4K|UHD)?'
    mapper:
      - tvg_name: TF1
        tvg_names:
          - '^\s*(FR)?[: |]?TF1!delimiter!!quality!\s*$'
        tvg_id: TF1.fr
        tvg_chno: "1"
        tvg_logo: https://emojipedia-us.s3.amazonaws.com/source/skype/289/shrimp_1f990.png
        group_title:
          - FR
          - TNT
      - tvg_name: TF1 Séries Films
        tvg_names:
          - '^.*TF1!delimiter!Series?!delimiter!Films?(!delimiter!!quality!)\s*$'
        tvg_id: TF1SeriesFilms.fr
        tvg_chno: "20"
        tvg_logo: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/google/350/shrimp_1f990.png
        group_title:
          - FR
          - TNT 
```
