### ISSUE TITLE
EPG does not support gz format

### ISSUE THREAD

**Issue by blockloop** [euzu/m3u-filter#69]
**Describe the bug**
Many IPTV providers provide the epg in epg.gz compression because of the sheer size of the data. 

**To Reproduce**

```
sources:
  - inputs:
      - enabled: true
        type: xtream
        persist: 'streamer_1_{}.m3u'
        epg_url: 'https://epg.streamer.com/epg.gz'
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

It's important to check the content-type header and also follow redirects. gz endpoints will return `Content-Type: application/gzip` but _many_ of them redirect
