### ISSUE TITLE
panic parsing int when using source type m3u

### ISSUE THREAD

**Issue by 36-chambers** [euzu/m3u-filter#70]
**Describe the bug**
```
m3u-filter-1  | thread 'main' panicked at src/model/playlist.rs:240:56:
m3u-filter-1  | called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }
```

**To Reproduce**

```
sources:
  - inputs:
      - enabled: true
        url: https://website.com/my.m3u
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
