### ISSUE TITLE
Unable to start in server mode (docker)

### ISSUE THREAD

**Issue by wanderleyteixeira** [euzu/m3u-filter#81]
**Describe the bug**
I am spin up a m3u-filter container in a Synology Docker env. Not sure what is missing here. Any guidance would be appreciated.

**Screenshots**
![Screenshot 2024-08-28 at 1 52 45 PM](https://github.com/user-attachments/assets/088409a9-656a-43f9-8236-fd1bf8bae5f8)

**Additional context**
![Screenshot 2024-08-28 at 1 53 05 PM](https://github.com/user-attachments/assets/6d8d294b-4bfc-40b9-8278-055c472ef148)

**Comment by euzu** [comment]
@wanderleyteixeira   you need config files matching your needs and settings. Examples are in the source. YOu can read the details in the wiki.  If you do not provide fully functional config files m3u filter wont work.

if you use docker to start m3u-filter, you need to mount a folder for the config files. You can find an example docker-compose file under the docker directory.
Asuming you have placed the files under `/opt/m3u-filter/` the compose file should look like:

```yaml
version: '3'
services:
  m3u-filter:
    container_name: m3u-filter
    image: ghcr.io/euzu/m3u-filter:latest
    working_dir: /
    volumes:
      - /opt/m3u-filter/data:/data
      - /opt/m3u-filter/config:/config
      - /opt/m3u-filter/backup:/backup
      - /opt/m3u-filter/downloads:/downloads
    environment:
      - TZ=Europe/Paris
    ports:
      - "8901:8901"
    restart: unless-stopped
```
