### ISSUE TITLE
Cannot read properties of null (reading 'user')

### ISSUE THREAD

**Issue by davidclaeysquinones** [euzu/m3u-filter#84]
Currently I'm using the docker image with id 196d44614baf.
Whenever I try to access the web UI I get  a blank page and I see the following message in the console : 
```
react-dom.production.min.js:189 TypeError: Cannot read properties of null (reading 'user')
    at user-view.tsx:39:47
    at Array.map (<anonymous>)
    at user-view.tsx:36:56
    at as (react-dom.production.min.js:244:332)
    at Su (react-dom.production.min.js:286:111)
    at react-dom.production.min.js:282:391
    at k (scheduler.production.min.js:13:203)
    at MessagePort.L (scheduler.production.min.js:14:128)
```

To be honest it's the first time I setup the program so it could be caused by something not being correctly setup.
In what direction should I look in order to solve the issue ?

**Comment by davidclaeysquinones** [comment]
I did not setup the api_proxy.yml since I understood that I didn't need it.
I did setup the users.txt file and put in a valid password hash.

Could you explain me concept-wise what's the  api_proxy.yml for ?

Right now I have the following files setup :

config.yml :

```
threads: 4
working_dir: ./data
api:
  host: 0.0.0.0
  port: 8901
  web_root: /web
web_ui_enabled: true
web_auth:
  enabled: true
  issuer: m3u_filter
  secret: secret
  userfile: user.txt

```
source.yml
```
sources:
- inputs:
    - url: 'http://redacted'
      name: iptv
  targets:
   - name: iptv
     output:
       - type: m3u
         filename: iptv.m3u
     filter: 'Group ~ ".*Spain.*" AND Group ~ ".*Belgium.*"'
```
mapping.yml

```
mappings:
     - id: Spain
        match_as_ascii: true
        mapper:
          - filter: 'Group ~ ".*Spain.*"'
```

Like I said it's my first time using this program and probably my config needs some adjustments.
If that's the case please feel free to point out my mistakes.
