### ISSUE TITLE
Add custom tag to Names and/or Titles

### ISSUE THREAD

**Issue by kumy** [euzu/m3u-filter#9]
**Is your feature request related to a problem? Please describe.**
As I'm using multiple providers, I like to know which one I'm currently using. So I used to tag my channels as: (mind the ` - PROVx` in `Name` and `Title`)

```m3u
#EXTINF:-1 tvg-id="TF1.fr" tvg-name="TF1 [HD] - PROV1" group-title="PROV1|FR|TNT" tvg-chno="1" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/TF1_logo_2013.svg/320px-TF1_logo_2013.svg.png", TF1 HD - PROV1
#EXTINF:-1 tvg-id="TF1.fr" tvg-name="TF1 [HD] - PROV2" group-title="PROV2|FR|TNT" tvg-chno="1" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/TF1_logo_2013.svg/320px-TF1_logo_2013.svg.png", TF1 HD - PROV2
```

**Describe the solution you'd like**
Be able per `config.yml` `source`, to add a specific suffix
```
  - input:
      url: 'prov1.m3u'
      persist: 'prov1.m3u.bak'
    targets:
      - filename: iptv-PROV1-FR_raw.m3u
        type: M3u
        processing_order: FRM
        filter: 'Name ~ "^FR\d+:"'
        options: { ignore_logo: false }
        rename:
          - { field: Name, new_name: "$1", pattern: "FR[0-9]+:(.*)" }
          - { field: Group, new_name: "$1", pattern: "(.*)" }
          - { field: Title, new_name: "$1", pattern: "FR[0-9]+:(.*)" }
        sort: { order: Asc }
        # HERE -->>
        tag:
            prefix: ''
            suffix: ' - PROV1'
        # <<-- HERE
        mapping:
          - France TNT
          - France Premium
          - Belgique
          - Suisse
          - Canada
          - RakutenTv
```

**Describe alternatives you've considered**
1. Without the mapping feature, I used to hack the `rename` to achieve that:
```
  - input:
      url: 'prov1.m3u'
      persist: 'prov1.m3u.bak'
    targets:
      - filename: iptv-PROV1-FR_raw.m3u
        type: M3u
        filter: 'Name ~ "^FR\d+:"'
        options: { ignore_logo: false }
        rename:
          - { field: Name, new_name: "$1 - PROV1", pattern: "FR[0-9]+:(.*)" }
          - { field: Group, new_name: "PROV1", pattern: "(.*)" }
          - { field: Title, new_name: "$1 - PROV1", pattern: "FR[0-9]+:(.*)" }
        sort: { order: Asc }
```

2.1 With the rename feature: when using default `FRM`, the `Rename hack` still works, but the mapping doesn't (The regex filters can be changed to permit matching

2.2 With the rename feature: when using `FMR`, the `Rename hack` works only on `Title` (`Name` only contains the mapped name - as expected), the mapping works, as I have the `Chno` and `Logo`

Both 2.1 an 2.2 are easily explainable, and are the expected result for the current implementation

**Additional context**
