### ISSUE TITLE
New Filter VOD and Series

### ISSUE THREAD

**Issue by iceman73** [euzu/m3u-filter#90]
**Describe the bug**
I changes my provider source from M#U to xtreme so I could take advantage of the new VOD and Series filters for non live TV content. The "live" and "vod" filters are working perfectly, but the "series" filter is returning nothing.

**To Reproduce**
1. Setup xtreme login to provider

```
  sources:
 
  - inputs:
     - type: xtream
       url: 'http://ccccc.com'
       headers:
         User-Agent: "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1"
         Accept: application/json
         Accept-Encoding: gzip
       username: user
       password: pass
```

2. Create Filter for VOD and Series:
```
- name: VOD
    value: (Type = vod)
  - name: TVTV
    value: (Type = series)
```
3. Create a TARGET for each filter:
```
targets:
        - name: TVVOD
          output:
            - type: m3u
              filename: tvvod.m3u
          filter: "!TVTV!"
          options: {ignore_logo: false}
          sort:
            groups:
              order: asc
        - name: MOVIES
          output:
            - type: m3u
              filename: nochannel.m3u
          filter: "!VOD!"
          options: {ignore_logo: false}
          sort:
            groups:
              order: asc
```

4. Create appropriate API for output:

```
user:
- target: MOVIES
  credentials:
  - username: movie
    password: movie1234
    proxy: reverse
    server: default
 - target: TVVOD
  credentials:
  - username: tv
    password: tv1234
    proxy: reverse
    server: default
```

**Expected behavior**
When I connect to pull m3u of for movies to see a list of VODs offered by my provider, which I do
When I connect to pull m3u for TVVOD, I get an empty list as no matches are made:

`#EXTM3U`

Debug Log is showing match found for series:

```
[2024-09-20T18:24:56Z DEBUG m3u_filter::filter] Match found: Type series-info
[2024-09-20T18:24:56Z DEBUG m3u_filter::filter] Match found: Type series-info
[2024-09-20T18:24:56Z DEBUG m3u_filter::filter] Match found: Type series-info
[2024-09-20T18:24:56Z DEBUG m3u_filter::filter] Match found: Type series-info
[2024-09-20T18:24:56Z DEBUG m3u_filter::filter] Match found: Type series-info
[2024-09-20T18:24:56Z DEBUG m3u_filter::filter] Match found: Type series-info
[2024-09-20T18:24:56Z DEBUG m3u_filter::filter] Match found: Type series-info

```
