### ISSUE TITLE
Not Excluding with Including

### ISSUE THREAD

**Issue by bennysp** [euzu/m3u-filter#94]
**Describe the bug**
I am trying to use the exclude (NOT) with an include, but no matter what I try, I seem to get more channels vs "less channels" which is what I am after is to exclude more channels.

**To Reproduce**
Add this to your templates:
(Note that for the `SKIPCHAN` I have tried Group, Title and Name already)
```yaml
templates:
  - name: US
    value: >- 
      Group ~ "^US.*"
  - name: SKIPCHAN
     value: >- 
       NOT(Name ~ ".*24/7.*") 
  - name: CHANALL
    value: >-
      !SKIPCHAN! AND
      !US!
...
targets:
...
      filter: '!CHANALL!'

```

If I leave to US alone (without the skipchan) then I get around 5K results. If I include the SKIPCHAN, I get 30K+.

**Expected behavior**
I expect that with each "NOT" combination, my results should decrease and not increase.

**Desktop (please complete the following information):**
m3u-filter: 2.0.4

**Smartphone (please complete the following information):**
NA

**Additional context**
I am not a regex guru, but I have tested the same query for `.*24/7.*` in the web tool and it finds those specific channels, so I would think wrapping "NOT" around it should produce the opposite effect.
